name: Publish artifact to Maven Central

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set for publishing to Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          mvn \
            -Ppublish-to-central \
            -B \
            deploy
      - name: Set up for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          server-id: github
          cache: maven
      - name: Publish to GitHub Packages
        run: |
          mvn \
            -Ppublish-to-github \
            -B \
            deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
